export class Parte{
    /* ID!: string; */
    NE!: string;
    /* DIA!: string;
    MES!: string;
    SHORA!: string;
    IHORA!: string;
    KMSALIDA!: string;
    KMINGRESO!: string;
    JEFE!: string;
    TPILOTO!: string;
    NPILOTO!: string;
    ORADIO!: string;
    TELEFONO!: string;
    CSERVICIO!: string;
    UCGBVP!: string;
    UPOLI!: string;
    MPOLI!: string;
    SAMU!: string;
    MSAMU!: string;
    SC!: string;
    MSC!: string;
    OE!: string;
    LE!: string;
    DE!: string;
    NUME!: string;
    MZE!: string;
    LTE!: string;
    URBE!: string;
    DTTOE!: string;
    TRASLDE!: string;
    MEDICORE!: string;
    ACOMP!: string;
    DNI!: string;
    PARENT!: string;
    PERSH!: string;
    PERSHM!: string;
    NOMBREPERS!: string;
    EDADPERS!: string;
    SEXOPERS!: string;
    DNIPERS!: string;
    PULSO!: string;
    RESP!: string;
    PARTERIAL!: string;
    SPO!: string;
    NEUROLOGICO!: string;
    REFLEJOC!: string;
    SINTG!: string;
    DIAGP!: string;
    TRATR!: string;
    MATERIALU!: string;
    OBSP!: string;
    OADD!: string; */
}